### ISSUE TITLE
the link of    **inspecting-the-dom** is not working 

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/incremental-development#4]
I've tried to open the link but doesn't work, I search in the code and the line code with the error is #166
 
166 -[inspecting-the-dom](https://hackyourfuture.be/inspecting-the-dom)

**Comment by colevandersWands** [comment]
Thanks for spotting this @rago89! here is the new link: https://hackyourfuturebelgium.github.io/inspecting-the-dom/

Your turn to send a pull request :)
