### ISSUE TITLE
fix the link

### ISSUE THREAD

**Issue by alinamarasca** [HackYourFutureBelgium/incremental-development#9]
Hey, Evan!
Please, fix the link to  **./development-strategy folder**  in [this description](https://github.com/HackYourFutureBelgium/incremental-development/blob/master/planning-and-collaborating/4-development-strategy.md)

**Comment by colevandersWands** [comment]
Good catch @alinamarasca! that's leftover from a previous draft. must have missed it while proofreading. 

Can you send a PR removing that last line?

**Comment by colevandersWands** [comment]
Fixed
